### ISSUE TITLE
about ImageNet-LT and iNaturalist

### ISSUE THREAD

**Issue by TalentedMUSE** [XuZhengzhuo/Prior-LT#2]
Where is the code? Could you please upload? Much thanks~

**Comment by XuZhengzhuo** [comment]
The large-scale datasets are implemented based on BagofTricks-LT(https://github.com/zhangyongshun/BagofTricks-LT). Please refer to this repo (combiner & loss) for reproduction.

**Comment by TalentedMUSE** [comment]
> The large-scale datasets are implemented based on BagofTricks-LT(https://github.com/zhangyongshun/BagofTricks-LT). Please refer to this repo (combiner & loss) for reproduction.

sorry, but I have tried your loss in BagofTricks-LT. When I set the reduction to 'none', there will be an error; when I delete the reduction parameter in Bayias loss, the result is not good (especially in ImageNet, it is very low).

**Comment by TalentedMUSE** [comment]
> The large-scale datasets are implemented based on BagofTricks-LT(https://github.com/zhangyongshun/BagofTricks-LT). Please refer to this repo (combiner & loss) for reproduction.


So would you please offer your modified version of BagofTricks-LT? Thanks~
